---
# Post-installation
# GIT Config
- name: Set GIT e-mail
  git_config:
    name: user.email
    scope: global
    value: "dalisoft@mail.ru"
- name: Set GIT username
  git_config:
    name: user.name
    scope: global
    value: "dalisoft"

# FNM Versions
- name: List installed fnm versions
  command: fnm ls
  register: fnmv_list
  changed_when: false
  check_mode: false
  tags:
    - install-fnm-version

- name: Installing fnm version
  shell: "fnm install {{ item }}"
  loop: "{{ fnm_versions }}"
  register: install_fnm_version
  until: install_fnm_version is successful
  when:
    - fnm_versions is defined
    - item not in fnmv_list.stdout
  tags:
    - install-fnm-version
