---
- name: Prepare packages
  set_fact:
    packages: "{{ (shared_packages | default([])) + (pacman_packages | default([])) }}"

# Packman packages
- name: Installing Pacman packages
  become: yes
  become_user: root
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ packages }}"
  register: install_pacman_package
  until: install_pacman_package is successful
  tags:
    - install-pacman-package
