# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 0
command_timeout = 3000

[battery]
disabled = true

[time]
disabled = true

[nix_shell]
disabled = true

[username]
disabled = true

[dotnet]
disabled = true

[nodejs]
symbol = "⬢ "
