---
# Snap packages
- name: List Snap packages
  command: snap list
  register: snap_installed_packages
  changed_when: false
  check_mode: false

- name: Installing Snap packages
  become: yes
  become_user: root
  snap:
    name: "{{ item }}"
    state: present
  loop: "{{ snap_packages }}"
  when:
    - snap_packages is defined
    - item not in snap_installed_packages
  register: install_snap_package
  until: install_snap_package is successful

- name: Installing Snap [classic] packages
  become: yes
  become_user: root
  snap:
    name: "{{ item }}"
    classic: yes
    state: present
  loop: "{{ snap_classic_packages }}"
  when:
    - snap_classic_packages is defined
    - item not in snap_installed_packages
  register: install_snap_classic_package
  until: install_snap_classic_package is successful
