exe 'source ~/.vim/_includes/boilerplate.vim'
exe 'source ~/.vim/_includes/wrapping.vim'

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'crusoexia/vim-monokai'
call plug#end()


" NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif

" Files default file assoc
autocmd BufNewFile,BufReadPost,FilterReadPost,FileReadPost *.txt set filetype=markdown
autocmd BufNewFile,BufReadPost *.styl set filetype=stylus

exe 'source ~/.vim/_includes/keymap.vim'

syntax on
colorscheme monokai



