---
- name: Include Linux Common playbook
  import_playbook: ../../../common/os/linux/playbook.yml

- name: Linux Desktop Playbook
  hosts: all
  gather_facts: yes
  become: false
  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    NFANCURVE_PATH: "$HOME/nfancurve"
    PATH: "/usr/local/bin:/snap/bin:$HOME/.fnm:$HOME/.local/bin:{{ ansible_env.PATH }}"
    MOZ_USE_OMTC: 1

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../../../common/os/shared/pre-task.yml

  tasks:
    - import_tasks: ../../../common/os/linux/_manjaro.yml
      when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjaro Linux'
    - import_tasks: ../../../common/os/linux/_debian.yml
      when: ansible_facts['os_family'] == 'Debian' or ansible_distribution == 'Pop!_OS'
    - import_tasks: .snap.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
    - import_tasks: .snap.yml
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
    # Post-installation
    - import_tasks: ../../../common/os/shared/post-task.yml
    - import_tasks: ../shared/post-task.yml
    - import_tasks: post-task.yml
