---
# Linux shared package names
# Shared names (DRY method)
shared_packages:
  # Browsers
  - epiphany-browser
  - firefox
  # Most needed desktop apps
  - 1password
  - vlc
  - telegram-desktop
  - octave
  - qbittorrent
  # Development tools
  - datagrip
  # HTTP / GraphQL clients
  - postman
  # Editors
  - sublime-text
  - code
  - webstorm
  # System utilities
  - gparted
  - speedify
  # KVM/Packages for Virtual Machines
  - bridge-utils
  # Tools
  - obs-studio
  - android-file-transfer
  # Gaming
  - steam

# APT (Debian/Ubuntu) packages
apt_keys:
  - https://keys.anydesk.com/repos/DEB-GPG-KEY
  - https://dl.google.com/linux/linux_signing_key.pub
  - https://download.sublimetext.com/sublimehq-pub.gpg
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  - https://packagecloud.io/shiftkey/desktop/gpgkey
  - https://get.speedify.com/pgp.key
  - https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
  - https://cli-assets.heroku.com/apt/release.key
  - https://dl.cloudsmith.io/public/balena/etcher/gpg.70528471AFF9A051.key

apt_ring_keys:
  # OBS Studio
  - keyserver: keyserver.ubuntu.com
    id: BC7345F522079769F5BBE987EFC71127F425E228
    # Android Studio
  - keyserver: keyserver.ubuntu.com
    id: ADC23DDFAE0436477B8CCDF54DEA8909DC6A13A3
    # Postman
  - keyserver:
    id: 5C3A446D08DA5A418703C6EDAAF3EBA4A836E4A3
    # qBittorrent
  - keyserver:
    id: 401E8827DA4E93E44C7D01E6D35164147CA69FC4
    # Android File Transfer for Linux
  - keyserver:
    id: 6D52190A4D3C9DCDF1CFE4140BB4A1B2FA1A38EB
    # NoobsLab
  - keyserver:
    id: 4FA44A478284A18C1BA4A9CAD530E028F59EAE4D

apt_repos:
  - deb http://ppa.launchpad.net/obsproject/obs-studio/ubuntu bionic main
  - deb http://ppa.launchpad.net/maarten-fonville/android-studio/ubuntu bionic main
  - deb http://ppa.launchpad.net/tiagohillebrandt/postman/ubuntu bionic main
  - deb http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu bionic main
  - deb http://ppa.launchpad.net/samoilov-lex/aftl-stable/ubuntu bionic main
  - deb http://ppa.launchpad.net/noobslab/apps/ubuntu bionic main
  - deb https://onepassword.s3.amazonaws.com/linux/debian edge main
  - deb http://deb.anydesk.com/ all main
  - deb http://dl.google.com/linux/chrome/deb/ stable main
  - deb https://download.sublimetext.com/ apt/stable/
  - deb https://packages.microsoft.com/repos/vscode stable main
  - "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_distribution_release|lower }} main"
  - deb http://apt.connectify.me/ speedify main
  - "deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic main"
  - deb https://cli-assets.heroku.com/apt
  - "deb https://dl.cloudsmith.io/public/balena/etcher/config.deb.txt?distro={{ ansible_distribution|lower }}&codename={{ ansible_distribution_release|lower }}&version={{ ansible_distribution_version }}&arch={{ ansible_architecture }}"
  - deb https://download.konghq.com/insomnia-ubuntu/ default all

apt_items:
  # PopOS polyfill
  - snapd
  - grub2-common
  - exfat-fuse
  - exfat-utils
  - software-properties-common
  - apt-transport-https
  # Python
  - python3-pyqt5
  # System utilities
  - flameshot
  - heroku
  # Most needed desktop apps
  - anydesk
  - balena-etcher-electron
  - xdman
  # Browser
  - google-chrome-stable
  # HTTP / GraphQL clients
  - insomnia
  # Mobile dev
  - android-studio-4.1
  # KVM/Packages for Virtual Machines
  - qemu
  - qemu-kvm
  - qemu-system
  - qemu-utils
  - libvirt-clients
  - libvirt-daemon
  - libvirt-daemon-system
  - virtinst
  - virt-manager
  - virtualbox
  - bridge-utils
  - cpu-checker
  # For AI Stuffs
  - nvidia-cuda-toolkit
  - nvidia-cuda-gdb
  - nvidia-cuda-dev
  - nvidia-cuda-doc
  # Java tools
  - adoptopenjdk-14-hotspot
  # Rust tools
  # - rust-analyzer
  # Dependencies for WebRTC
  - libavdevice-dev
  - libavfilter-dev
  - libopus-dev
  - libvpx-dev
  - libsrtp2-dev
  - pkg-config

# Snap packages
snap_packages:
  - starship

snap_classic_packages:
  - deno
  - gitkraken
  - altair
  - clockify-cli
  - ora

# Pacman packages
pacman_packages:
  # Polyfills
  - exfat-dkms-git
  # Fonts
  - ttf-fira-code
  # Other desktop tools
  - heroku-cli
  # Most needed desktop apps
  - flameshot-git
  - anydesk-bin
  - balena-etcher
  - google-chrome
  # Management
  - ganttproject
  - clockify-desktop
  # Downloaders
  - freedownloadmanager
  - 4kvideodownloader
  # Development tools
  - gitkraken
  # HTTP / GraphQL clients
  - insomnia-bin
  - altair
  # Editors / IDE
  - onivim2
  - android-studio
  # Messengers
  - slack-desktop
  # KVM/Packages for Virtual Machines
  - virt-manager
  - virtualbox-bin
  - qemu
  - qemu-arch-extra
  - vde2
  - iptables
  - ebtables
  - ovmf
  - dnsmasq
  - bridge-utils
  - openbsd-netcat
  # For AI Stuffs
  - cuda
  # Java tools
  - jdk11-adoptopenjdk
  # Python tools
  - anaconda
  # Rust tools
  - rust-analyzer
