let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1

set nocompatible

call plug#begin('~/.vim/plugged')

Plug 'crusoexia/vim-monokai'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'editorconfig/editorconfig-vim'
Plug 'elzr/vim-json'
Plug 'tpope/vim-dotenv'

call plug#end()

set encoding=UTF-8
set background=dark
colorscheme monokai
set t_Co=256
set guifont=Fira\ Code\ Regular:h13

set number
set incsearch
set hlsearch

set laststatus=2
set noswapfile
set autoread
set autoindent
set smartindent
set rnu
set splitright
set splitbelow

syntax enable
